name: macos build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup toolchain install stable --profile minimal
      - uses: Swatinem/rust-cache@v2
      - uses: extractions/setup-just@v2
      - name: build
        run: just build
      - uses: actions/upload-artifact@v4
        with:
          name: macos-build
          path: |
            target/release/fishus-bevy
          retention-days: ${{ github.event_name == 'pull_request' && 1 || 90 }}
