name: windows build

permissions:
  contents: write

on:
  release:
    types:
      - prereleased
      - released
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup toolchain install nightly --profile minimal
      - uses: Swatinem/rust-cache@v2
      - uses: extractions/setup-just@v2
      - name: build
        run: just build
      - uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: |
            target/release/fishus-bevy.exe
          retention-days: ${{ github.event_name == 'pull_request' && 1 || 90 }}
      - uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: |
            target/release/fishus-bevy.exe
            LICENSE
